RafflesChart/Models/ActivateFunctionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace RafflesChart.Models {
    public class ActivateFunctionViewModel {
        [DisplayName("Bull Bear Tests")]
        public string BullBearTests { get; set; }

        [DisplayName("Back Tests")]
        public string BackTests { get; set; }

        [DisplayName("Pattern Scanners")]
        public string PatternScanners { get; set; }

        public string Scanners { get; set; }

        public string Markets { get; set; }

        public string Indicators { get; set; }

        [DisplayName("Expired Date")]
        public DateTime? ExpiredDate { get; set; }

        public HttpPostedFileBase Users { get; set; }

        [DisplayName("Replace Records")]
        public bool ReplaceRecords { get; set; }
    }
}

RafflesChart/Models/Scheme.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace RafflesChart.Models {
    public class Scheme {
        public int Id { get; set; }

        public String Description { get; set; }

        public String Name { get; set; }

        public string Markets { get; set; }

        public string Indicators { get; set; }

        [DisplayName("Bull Bear Tests")]
        public string BullBearTests { get; set; }

        [DisplayName("Back Tests")]
        public string BackTests { get; set; }

        [DisplayName("Pattern Scanners")]
        public string PatternScanners { get; set; }

        public string Scanners { get; set; }

        public bool ScannerFlag   {get;set;}
        public bool CustomIndicatorsFlag  {get;set;}
        public bool LiveFlag   {get;set;}
        public bool CIAddFlag   {get;set;}
        public bool ScannerAddFlag   {get;set;}
        public bool SignalAddFlag   {get;set;}
        public bool TrendAddFlag   {get;set;}
        public bool PatternAddFlag   {get;set;}


    }
}

RafflesChart/Models/SchemeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RafflesChart.Models {
    public class SchemeViewModel {
        public int Id { get; set; }

        public String Description { get; set; }

        public String Name { get; set; }        
        
        public string Markets { get; set; }

        public string Indicators { get; set; }
        

        [DisplayName("Bull Bear Tests")]
        public string BullBearTests { get; set; }
        
        [DisplayName("Back Tests")]
        public string BackTests { get; set; }
                
        [DisplayName("Pattern Scanners")]
        public string PatternScanners { get; set; }

        public string Scanners { get; set; }

        [DisplayName("Scanner")]
        public bool ScannerFlag { get; set; }
        [DisplayName("Custom Indicators")]
        public bool CustomIndicatorsFlag { get; set; }

        [DisplayName("Live")]
        public bool LiveFlag { get; set; }

        [DisplayName("CI Add")]
        public bool CIAddFlag { get; set; }

        [DisplayName("Scanner Add")]
        public bool ScannerAddFlag { get; set; }

        [DisplayName("Signal Add")]
        public bool SignalAddFlag { get; set; }

        [DisplayName("Trend Add")]
        public bool TrendAddFlag { get; set; }

        [DisplayName("Pattern Add")]
        public bool PatternAddFlag { get; set; }
    }
}

RafflesChart/Controllers/SchemesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RafflesChart.Models;
using NPOI.HSSF.UserModel;
using System.IO;
using NPOI.XSSF.UserModel;
using Microsoft.AspNet.Identity;
using System.Web.Security;
using EntityFramework.Extensions;
using RafflesChart.Extensions;
using Newtonsoft.Json;

namespace RafflesChart.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SchemesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Schemes
        public  ActionResult IndexA()
        {
            return View();
        }

        // GET: Schemes
        [HttpGet]
        public async Task<ActionResult> SchemeList()
        {
            var ls = await db.Schemes.ToListAsync();

            var ret = JsonConvert.SerializeObject (ls);
            return Content(ret);
        }

        // GET: Schemes
        public async Task<ActionResult> Index()
        {
            return View(await db.Schemes.ToListAsync());
        }

        [HttpGet]
        public async Task<ActionResult> DetailJson(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Scheme scheme = await db.Schemes
                                        .Where(s => s.Id == id)
                                    .FirstOrDefaultAsync();
            if (scheme == null)
            {
                return HttpNotFound();
            }

            var vm = GetSchemeViewModel(scheme);

            return Json(vm , JsonRequestBehavior.AllowGet);
        }

        // GET: Schemes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Scheme scheme = await db.Schemes
                                        .Where(s => s.Id == id)
                                        .FirstOrDefaultAsync();
            if (scheme == null)
            {
                return HttpNotFound();
            }

            var vm = GetSchemeViewModel(scheme);

            return View(vm);
        }

       

        // GET: Schemes/Create
        public ActionResult Create()
        {
            var vm = new SchemeViewModel();
            return View(vm);
        }

         [HttpGet]  //[ValidateAntiForgeryToken]        
        public  ActionResult Sample()
        {
             SchemeViewModel viewModel = new SchemeViewModel();
             viewModel.Name = "test";
             return Content(JsonConvert.SerializeObject(viewModel));
         }

        // POST: Schemes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]  //[ValidateAntiForgeryToken]        
        public async Task<ActionResult> Create(SchemeViewModel viewModel)
        {
          
            if (ModelState.IsValid)
            {
                var scheme = new Scheme() { 
                    Name = viewModel.Name,
                    Description = viewModel.Description,
                    Markets = viewModel.Markets,
                    Indicators = viewModel.Indicators,
                    BullBearTests = viewModel.BullBearTests,
                    BackTests = viewModel.BackTests,
                    PatternScanners = viewModel.PatternScanners,
                    Scanners = viewModel.Scanners,
                    ScannerFlag = viewModel.ScannerFlag,
                    CustomIndicatorsFlag = viewModel.CustomIndicatorsFlag,
                    LiveFlag = viewModel.LiveFlag,
                    CIAddFlag = viewModel.CIAddFlag,
                    ScannerAddFlag = viewModel.ScannerAddFlag,
                    SignalAddFlag = viewModel.SignalAddFlag,
                    TrendAddFlag = viewModel.TrendAddFlag,
                    PatternAddFlag = viewModel.PatternAddFlag                       
                };

                db.Schemes.Add(scheme);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Schemes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheme scheme = await db.Schemes                                        
                                        .Where(s => s.Id == id)
                                        .FirstOrDefaultAsync();
            if (scheme == null)
            {
                return HttpNotFound();
            }           
            
            var vm = new SchemeViewModel() {
                Id = scheme.Id,
                Name = scheme.Name,
                Description = scheme.Description,
                Markets = scheme.Markets,
                Indicators = scheme.Indicators,
                BullBearTests = scheme.BullBearTests,
                BackTests = scheme.BackTests,
                PatternScanners = scheme.PatternScanners,
                Scanners = scheme.Scanners,
                ScannerFlag = scheme.ScannerFlag,
                CustomIndicatorsFlag = scheme.CustomIndicatorsFlag,
                LiveFlag = scheme.LiveFlag,
                CIAddFlag = scheme.CIAddFlag,
                ScannerAddFlag = scheme.ScannerAddFlag,
                SignalAddFlag = scheme.SignalAddFlag,
                TrendAddFlag = scheme.TrendAddFlag,
                PatternAddFlag = scheme.PatternAddFlag
            };

            return View(vm);
        }

        // POST: Schemes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(SchemeViewModel viewModel) {
            if (ModelState.IsValid) {


                var users = await (from user in db.Users 
                            from chartuser in db.ChartUsers 
                            where user.Email == chartuser.Login && 
                                    user.SchemeId == viewModel.Id
                            select new{chartuser,user} ).ToArrayAsync() ;
                foreach (var user in users)
                {
                    user.chartuser.Live = viewModel.LiveFlag;
                    user.chartuser.CI_Add = viewModel.CIAddFlag;
                    user.chartuser.CustomIndicators = viewModel.CustomIndicatorsFlag;
                    user.chartuser.Pattern_Add = viewModel.PatternAddFlag;
                    user.chartuser.Scanner = viewModel.ScannerFlag;
                    user.chartuser.Scanner_Add = viewModel.ScannerAddFlag;
                    user.chartuser.Signal_Add = viewModel.SignalAddFlag;
                    user.chartuser.Trend_Add = viewModel.TrendAddFlag;
                    user.user.ModifiedDate = DateTime.Now;
                }

                Scheme scheme = await db.Schemes
                                        .Where(s => s.Id == viewModel.Id)
                                        .FirstOrDefaultAsync();
                
                scheme.Name = viewModel.Name;
                scheme.Description = viewModel.Description;
                scheme.Markets = viewModel.Markets;
                scheme.Indicators = viewModel.Indicators;
                scheme.BullBearTests = viewModel.BullBearTests;
                scheme.BackTests = viewModel.BackTests;
                scheme.PatternScanners = viewModel.PatternScanners;
                scheme.Scanners = viewModel.Scanners;
                scheme.LiveFlag = viewModel.LiveFlag;
                scheme.ScannerFlag = viewModel.ScannerFlag;
                scheme.CustomIndicatorsFlag = viewModel.CustomIndicatorsFlag;
                scheme.CIAddFlag = viewModel.CIAddFlag;
                scheme.ScannerAddFlag = viewModel.ScannerAddFlag;
                scheme.SignalAddFlag = viewModel.SignalAddFlag;
                scheme.TrendAddFlag = viewModel.TrendAddFlag;
                scheme.PatternAddFlag = viewModel.PatternAddFlag;

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Schemes/Delete/5
        [HttpPost]
        public async Task<ActionResult> DeleteA(int? id)
        {
            Scheme scheme = await db.Schemes.FindAsync(id);
            var vm = new { deleteScheme = scheme };
            
            db.Schemes.Remove(scheme);
            await db.SaveChangesAsync();

            
            var j = JsonConvert.SerializeObject(vm);

            return Content(j);
        }

        // GET: Schemes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheme scheme = await db.Schemes
                                        .Where(s => s.Id == id)
                                        .FirstOrDefaultAsync();
            if (scheme == null)
            {
                return HttpNotFound();
            }

            var vm = GetSchemeViewModel(scheme);
            return View(vm);
        }

        // POST: Schemes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Scheme scheme = await db.Schemes.FindAsync(id);

RafflesChart/Views/Schemes/Activate.cshtml
@model RafflesChart.Models.ActivateSchemeViewModel

@{
    ViewBag.Title = "Activate Scheme";
}

<h2>Activate Scheme</h2>


@using (Html.BeginForm("Activate", "Schemes", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedSchemeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedSchemeId, Model.Schemes, new { @class = "form-control" })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="label label-info img-button" value="1" name="dtmonth">1 Month</label>
                <label class="label label-info img-button" value="12" name="dtmonth">1 Year</label>
                <label class="label label-info img-button" value="3" name="dtmonth">3 Months</label>

                @Html.EditorFor(model => model.ExpiredDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiredDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Users" id="Users" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datetimepicker")
    <script type="text/javascript">
        (function ($, window) {
            $(function () {
                $('#ExpiredDate').datetimepicker({
                    format: 'm/d/Y h:i:s A'
                });
                $('label[name = dtmonth]').click(function () {
                    var chk = $(this).attr("value");
                    console.log(chk);
                    $.ajax({
                        url: '/Events/GetEventDate',
                        type: 'POST',
                        data: { 'i': chk },
                        success: function myfunction(data) {
                            $('#ExpiredDate').val(data);
                        }
                    });

                });
            });
        })(jQuery, window);
        
    </script>
}

RafflesChart/Views/Schemes/ActivateErrorEmails.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "ActivateErrorEmails";
}


<hr />
                      <h2>Error Emails</h2>
<ul>
    @foreach (var email in Model) {
        <li>@email</li>
    }
</ul>

RafflesChart/Views/Schemes/ActivateFunction.cshtml
@model RafflesChart.Models.ActivateFunctionViewModel

@{
    ViewBag.Title = "Activate Single Function";
}

<h2>Activate Single Function</h2>

@using (Html.BeginForm("ActivateFunction", "Schemes", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Markets, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Markets, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Markets, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Indicators, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Indicators, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Indicators, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BullBearTests, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BullBearTests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BullBearTests, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BackTests, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BackTests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BackTests, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatternScanners, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatternScanners, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatternScanners, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Scanners, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Scanners, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Scanners, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <label class="label label-info img-button" value="1" name="dtmonth">1 Month</label>
                <label class="label label-info img-button" value="12" name="dtmonth">1 Year</label>
                <label class="label label-info img-button" value="3" name="dtmonth">3 Months</label>

                @Html.EditorFor(model => model.ExpiredDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiredDate, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Users" id="Users" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">
                &nbsp;
            </label>
            <div class="col-md-10">

                @Html.CheckBoxFor(model => model.ReplaceRecords, new { htmlAttributes = new { @text = Model.ReplaceRecords } })
                @Html.LabelFor(model => model.ReplaceRecords)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datetimepicker")
    <script type="text/javascript">
        (function ($, window) {
            $(function () {
                $('#ExpiredDate').datetimepicker({
                    format: 'm/d/Y h:i:s A'
                });

                $('label[name = dtmonth]').click(function () {
                    var chk = $(this).attr("value");
                    console.log(chk);
                    $.ajax({
                        url: '/Events/GetEventDate',
                        type: 'POST',
                        data: { 'i': chk },
                        success: function myfunction(data) {
                            $('#ExpiredDate').val(data);
                        }
                    });

                });
            });
        })(jQuery, window);

    </script>
}

RafflesChart/Views/Schemes/Create.cshtml
@model RafflesChart.Models.SchemeViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) {
    @*@Html.AntiForgeryToken()*@

    <div ng-controller="SchemeController" class="form-horizontal">
        <h4>Scheme</h4>
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
        
        @Html.Partial("_CreateOrEditA", Model)

        @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>*@
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RafflesChart/Views/Schemes/Delete.cshtml
@model RafflesChart.Models.SchemeViewModel

@{
    ViewBag.Title = "Delete";
}

@section Styles {
    <style type="text/css">
        a.search-choice-close {
            display: none !important;
        }
    </style>
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Scheme</h4>
    <hr />

    @Html.Partial("_Details", Model)

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RafflesChart/Views/Schemes/Details.cshtml
@model RafflesChart.Models.SchemeViewModel

@{
    ViewBag.Title = "Details";
}

@section Styles {
    <style type="text/css">
        a.search-choice-close {
            display: none!important;
        }
    </style>
}

<h2>Details</h2>

<div>
    <h4>Scheme</h4>
    <hr />
    
    @Html.Partial("_Details", Model)
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RafflesChart/Views/Schemes/Edit.cshtml
@model RafflesChart.Models.SchemeViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Scheme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @Html.Partial("_CreateOrEdit", Model)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RafflesChart/Views/Schemes/Index.cshtml
@model IEnumerable<RafflesChart.Models.Scheme>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Markets)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Indicators)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BullBearTests)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BackTests)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatternScanners)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Scanners)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.ScannerFlag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomIndicatorsFlag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LiveFlag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CIAddFlag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScannerAddFlag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SignalAddFlag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrendAddFlag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatternAddFlag)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.Markets)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Indicators)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BullBearTests)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BackTests)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PatternScanners)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Scanners)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.ScannerFlag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomIndicatorsFlag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LiveFlag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CIAddFlag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ScannerAddFlag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SignalAddFlag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrendAddFlag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PatternAddFlag)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

RafflesChart/Views/Schemes/IndexA.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table" ng-controller="SchemeController">
    <tr>
        <th> &nbsp;</th>
        <th>Name</th>
        <th>Description</th>
        <th>Markets</th>
        <th>Indicators</th>
        <th>Bull Bear Test</th>
        <th>Back Test</th>
        <th>Patterns Scanners</th>
        <th>Scanner</th>
    </tr>
    <tr ng-repeat="scheme in schemelist">
        <td><img class="img-button" title="delete scheme" src="~/Content/close_16x16.png" ng-click="removeScheme(scheme.schemeid)" /> </td>
        <td>{{scheme.name}}</td>
        <td>{{scheme.description}}</td>
        <td>{{scheme.usermarkets}}</td>
        <td>{{scheme.userindicators}}</td>
        <td>{{scheme.userbullbeartest}}</td>
        <td>{{scheme.userbacktest}}</td>
        <td>{{scheme.patternscanners}}</td>
        <td>{{scheme.scanners}}</td>
    </tr>
    </table>
<script type="text/javascript" src="~/Scripts/app/scheme.js"></script>

RafflesChart/Views/Schemes/SchemeUserData.cshtml
@model RafflesChart.Models.SchemeUserViewModel

<h3>User Markets</h3>
@foreach (var item in Model.UserMarkets)
{

    <div>@item</div>
}



<h3>User Indicators</h3>
@foreach (var item in Model.UserIndicators)
{

    <div>@item</div>
}

<h3>User BullBear Tests</h3>
@foreach (var item in Model.UserBullBearTests)
{

    <div>@item</div>
}

<h3>User Back Tests</h3>
@foreach (var item in Model.UserBackTests)
{

    <div>@item</div>
}

<h3>User Patternscanners</h3>
@foreach (var item in Model.UserPatternScanners)
{

    <div>@item</div>
}

<h3>User Scanners</h3>
@foreach (var item in Model.UserScanners)
{

    <div>@item</div>
}