RafflesChart/Controllers/ManageSubscriptionController.cs
using RafflesChart.Models;
using RafflesChart.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RafflesChart.Controllers
{
    [Authorize]
    public class ManageSubscriptionController : Controller
    {
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateInput(false)]
        public ActionResult Add(SubscriptionEntryViewModel vm)
        {
            using (var db= new ApplicationDbContext())
            {
                var subscription = new Subscription();
                subscription.Name = vm.Name;
                subscription.Price = vm.Price;
                subscription.Detail = vm.Detail;
                subscription.Description = vm.Description;
                var dtnow = DateTime.Now;
                subscription.CreatedDate = dtnow;
                subscription.UpdatedDate = dtnow;
                subscription.Status = vm.Status;
                db.Subscriptions.Add(subscription);
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }

        public ActionResult Add()
        {
            return View();
        }
        public ActionResult Edit(int Id)
        {
            using (var db = new ApplicationDbContext())
            {
                var vm = db.Subscriptions.FirstOrDefault(x=> x.Id == Id);

                return View(vm);
            }            
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateInput(false)]
        public ActionResult Edit(Subscription vm)
        {
            using (var db = new ApplicationDbContext())
            {
                var subscription = db.Subscriptions.FirstOrDefault(x => x.Id == vm.Id);

                subscription.Name = vm.Name;
                subscription.Price = vm.Price;
                subscription.Description = vm.Description;
                subscription.Detail = vm.Detail;
                subscription.UpdatedDate = DateTime.Now;
                subscription.Status = vm.Status;
                db.SaveChanges();
                return RedirectToAction("List");
            }
        }
         public ActionResult Payment(){
             return View();
         }
         
        public ActionResult List()
        {
            using (var db = new ApplicationDbContext())
            {
                var vm = db.Subscriptions.ToList();

                return View(vm);
            }            
        }

        [Authorize(Roles = "Admin")]
        public ActionResult GetPaymentsJson(string paymentdate,
                               string username,string useremail,string subscriptionname,string paypalref )
        {
            var dtstart = DateTime.ParseExact("1 Jan 2014", "d MMM yyyy", null);
            var dtend = DateTime.Now;
            DateTime d1 = new DateTime(1970, 1, 1);
            if (paymentdate != null && paymentdate.Length == 23)
            {
                string strstart = paymentdate.Split(" - ".ToCharArray())[0];
                string strend = paymentdate.Split(" - ".ToCharArray())[3];
                DateTime.TryParseExact(strstart, new string[] { "MM/dd/yyyy" }, null, System.Globalization.DateTimeStyles.None, out dtstart);
                bool parseok = DateTime.TryParseExact(strend, new string[] { "MM/dd/yyyy" }, null, System.Globalization.DateTimeStyles.None, out dtend);
                if (parseok)
                {
                    dtend = dtend.Date.AddDays(1);
                }
            }

            using (var context = new ApplicationDbContext())
            {
                var subscriptions = context.UserSubscriptions.AsQueryable();
                var users = context.Users.AsQueryable();
                if (!string.IsNullOrEmpty(username))
                {
                    users = users.Where(u => u.Name.Contains(username));
                }
                if (!string.IsNullOrEmpty(useremail))
                {
                    users = users.Where(u => u.Email.Contains(useremail));
                }
                if (!string.IsNullOrEmpty(paypalref))
                {
                    subscriptions = subscriptions.Where(x => x.PaypalRef.Contains(paypalref));
                }

                if (!string.IsNullOrEmpty(subscriptionname))
                {
                    subscriptions = subscriptions.Where(x => x.ItemName.Contains(subscriptionname));
                }
                
                 var vm =  from u in users
                           from s in subscriptions
                           where s.CreatedDate >= dtstart && s.CreatedDate <= dtend
                            && s.UserId == u.UserName
                            select new { UserEmail = u.Email , UserName= u.Name ,
                                        SubscriptionName = s.ItemName , 
                                        Price = s.Price,
                                        Month =s.Month, 
                                        CreatedDate = s.CreatedDate,
                                        PaypalRef = s.PaypalRef};

                 var ngvm = vm.ToList().Select(x => new
                 {
                     x.UserName,
                     x.UserEmail,
                     x.SubscriptionName,
                     x.Price,
                     x.Month,
                     x.PaypalRef,
                     CreatedDate = new TimeSpan(x.CreatedDate.AddHours(-8).Ticks - d1.Ticks).TotalMilliseconds,
                 });


                 return Json(ngvm, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

RafflesChart/Views/ManageSubscription/Add.cshtml
@{
    ViewBag.Title = "Add";
}
@section Styles{
    @Styles.Render("~/Content/css")
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/summernote.css" rel="stylesheet" />
    <style>
        .pageselect {
            height: 40px;
        }
    </style>
}
    <h2 style="text-align:left">Add</h2>

@using( Html.BeginForm("Add","ManageSubscription"))
{

<div class="control-group">
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Name
            </label>
        </div>
        <div class="col-xs-4">
            <input type="text" name="Name" value="" class="form-control" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Total Amount
            </label>
        </div>
        <div class="col-xs-4">
            <input type="text" name="Price" value="" id="Price" class="form-control" />
            @Html.ValidationMessage("Price")
        </div>
    </div>
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Description
            </label>
        </div>
        <div class="col-xs-4">
            <input type="text" name="Description" id="Description" value="" class="form-control" />
            @Html.ValidationMessage("Description")
        </div>
    </div>
   
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Details
            </label>
        </div>
        <div class="col-xs-4">
            
            <textarea class="input-block-level" id="summernote" name="Detail" rows="18"></textarea>
        </div>
    </div>
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Status
            </label>
        </div>
        <div class="col-xs-4">
            @{
    var statuspick = new List<SelectListItem>(){
                    new SelectListItem(){Text="Sale",Value="Sale"},
                    new SelectListItem(){Text="NotForSale",Value="NotForSale"}
                };
            }
            @Html.DropDownList("Status",statuspick, new { @class = "form-control" })
        </div>
    </div>

    <div class="row form-group">
        <div class="col-xs-2">
            &nbsp;
        </div>
        <div class="col-xs-4">
            <input type="submit" class="btn btn-primary" value="Add" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-xs-2">
           @Html.ActionLink("View List" , "List")
        </div>
        </div>
 </div>  
}

@section Scripts{

    <script src="~/Scripts/summernote.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#summernote').summernote({ height: "500px" });
          
        });
        var postForm = function () {
            var content = $('textarea[name="Detail"]').html($('#summernote').code());
        }
    </script>
}

RafflesChart/Views/ManageSubscription/Edit.cshtml
@model RafflesChart.Models.Subscription
@{
    ViewBag.Title = "Add";
}
@section Styles{
    @Styles.Render("~/Content/css")
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/summernote.css" rel="stylesheet" />
    <style>
        .pageselect {
            height: 40px;
        }
    </style>
}
<h2>Add</h2>
@using( Html.BeginForm("Edit","ManageSubscription"))
{

<div class="control-group">
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Name
                @Html.HiddenFor(m=> m.Id)
            </label>
        </div>
        <div class="col-xs-4">
            @Html.EditorFor(model => model.Name, new {htmlAttributes = new { @class = "form-control" }})
        </div>
    </div>
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Total Amount
            </label>
        </div>
        <div class="col-xs-4">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @id = "Price" } })
        </div>
    </div>
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Description
            </label>
        </div>
        <div class="col-xs-4">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @id = "Quantity" } })
        </div>
    </div>
   
    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Details
            </label>
        </div>
        <div class="col-xs-4">
            <textarea class="input-block-level" id="summernote" name="Detail" rows="18">@Model.Detail</textarea>
        </div>
    </div>

    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Status
            </label>
        </div>
        <div class="col-xs-4">
            @{
                    var statuspick = new List<SelectListItem>(){
                    new SelectListItem(){Text="Sale",Value="Sale"},
                    new SelectListItem(){Text="NotForSale",Value="NotForSale"}
                };
            }
            @Html.DropDownListFor(model => model.Status, statuspick, new {@class="form-control" })
        </div>
    </div>

    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Created
            </label>
        </div>
        <div class="col-xs-4">
            @Model.CreatedDate
        </div>
    </div>

    <div class="row form-group">
        <div class="col-xs-2">
            <label>
                Updated
            </label>
        </div>
        <div class="col-xs-4">
            @Model.UpdatedDate
        </div>
    </div>
     
   
    <div class="row form-group">
        <div class="col-xs-2">
            &nbsp;
        </div>
        <div class="col-xs-4">
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
    </div>

</div>
}

@section Scripts{

    <script src="~/Scripts/summernote.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#Total').val($('#Quantity').val() * $('#Price').val());
            $('#summernote').summernote({ height: "500px" });
        });
        var postForm = function () {
            var content = $('textarea[name="Detail"]').html($('#summernote').code());
        }
    </script>
}

RafflesChart/Views/ManageSubscription/List.cshtml
@model IEnumerable<RafflesChart.Models.Subscription>
@{
    ViewBag.Title = "List";
}

<h2>List</h2>
<table class="table">
    <thead>
        <th>
            Name
        </th>
        <th>
            Price
        </th>
        <th>
            Detail
        </th>
        <th>
            Status
        </th>
        <th>
            Created Date
        </th>
        <th>
            Updated Date
        </th>
    </thead>
   

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Price
            </td>
            <td>
                @Html.Raw(item.Detail)
            </td>
            <td>
                @item.Status
            </td>
            <td>
                @item.CreatedDate
            </td>
            <td>
                @item.UpdatedDate
            </td>
            <td>
                @Html.ActionLink("edit", "Edit",  new { @Id = item.Id})
            </td>
        </tr>
    }

</table>

RafflesChart/Views/ManageSubscription/Payment.cshtml
@{
    ViewBag.Title = "Payment";
}
@section Styles{
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/daterangepicker-bs3.css" rel="stylesheet" />
}
<h2>Payment</h2>

<div ng-controller="paymentcontroller">
    <div>
        <div class="row form-group">
            <div class="col-xs-2">
                User Name
            </div>
            <div class="col-xs-4">
                <input type=" text" ng-model="username" class="form-control" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-2">
                Email
            </div>
            <div class="col-xs-4">
                <input type="text" ng-model="useremail" class="form-control" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-2">
                Subscription
            </div>
            <div class="col-xs-4">
                <input type="text" ng-model="subscriptioname" class="form-control" />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-2">
                Paypal Ref
            </div>
            <div class="col-xs-4">
                <input type="text" ng-model="paypalref" class="form-control" />
            </div>
        </div>
       
        <div class="row form-group">
            <div class="col-xs-2">
                Date
            </div>
            <div class="col-xs-4">
                <div class="input-prepend input-group">
                    <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span><input ng-model="paymentdate" type="text" style="width: 200px" name="paymentdate" id="paymentdate" class="form-control" />

                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-2">
                Subscription
            </div>
            <div class="col-xs-4">
                <input type="submit" ng-click="getPayments();" class="btn btn-primary"   />
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
        <th>
            User Name
        </th>
        <th>
            Email
        </th>
        <th>
            Subscription
        </th>
        <th>
            Price
        </th>
        <th>
            Month
        </th>
        <th>
            Total
        </th>
        <th>
            Paypal Ref
        </th>
        <th>
            Payment Date
        </th>
        </thead>


        <tr ng-repeat="payment in payments">
            <td>
                {{payment.UserName}}
            </td>
            <td>
                {{payment.UserEmail}}
            </td>
            <td>
                {{payment.SubscriptionName}}
            </td>
            <td>
                {{payment.Price}}
            </td>
            <td>
                {{payment.Month}}
            </td>
            <td>
                {{payment.Price * payment.Month}}
            </td>
            <td>
                {{payment.PaypalRef}}
            </td>
            <td>
                {{payment.CreatedDate | date:'medium'}}
            </td>
        </tr>
  

    </table>

</div>
@section scripts{
<script src="~/Scripts/app/app.js"></script>
    <script src="~/Scripts/app/payment.js"></script>
<script src="~/Scripts/moment.min.js"></script>
<script src="~/Scripts/daterangepicker.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#paymentdate').daterangepicker({
            ranges: {
                'Today': [new Date(), new Date()],
                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                'Last 7 Days': [moment().subtract('days', 6), new Date()],
                'Last 30 Days': [moment().subtract('days', 29), new Date()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
            }
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
            $('#paymentdate').change();
        });
    });
</script>
}